app:
  gmail:
    email: kampustesttask@gmail.com
    password: krzbtnmzihvzsrng
  scheduler:
    enabled: false

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kampus-test-task
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 29617503142-1r4junhf1v46vk4t5r2p52ikrj8pilae.apps.googleusercontent.com
            client-secret: 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
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

