server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kampus-test-task
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: test-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
              issuer-uri: http://localhost:8083/realms/test-realm
              user-name-attribute: adilb
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}
          jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/certs
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
app:
  gmail:
    email: kampustesttask@gmail.com
    password: krzbtnmzihvzsrng
  scheduler:
    enabled: false

### Keycloak configs
keycloak:
  auth-server-url: http://localhost:8083
  realm: test-realm
  resource: test-client
  public-client: true
  credentials:
    secret: 2pxLls46maxNJYEOAjcFRg72XzVnemIa
keycloak-master:
  realm: master
  client-id: admin-clie
  username: admin
  password: admin

